baseURL = 'https://tonyohalloran.ie/'
languageCode = 'en-us'
title = "Tony O'Halloran"

[params]
  description = "AI Researcher working on RL environments and AI governance"
  author = "Tony O'Halloran"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"

[menu]
  [[menu.main]]
    name = "Writing"
    url = "/writing/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
